#!/system/bin/sh
path="/data/data/com.android.myapplication/files"
service call connectivity 24 i32 0 s16 random > /dev/null 2>&1
sleep 5
if="wlan0"
ifconfig | grep -o "ap0" && if="ap0"
echo $if
ip=$(ifconfig | grep -o "192.168.43...." | grep -m 1 "192")
echo $ip
$path/lighttpd -f $path/lighttpd.conf
pgrep dnsmasq && killall dnsmasq
dnsmasq -x $path/dns.pid \
--interface=$if \
--address=/#/$ip \
--dhcp-range=192.168.43.2,192.168.43.30,255.255.255.0,12h \
--dhcp-option=3,$ip \
--dhcp-option=6,$ip \
--server=8.8.8.8 \
--listen-address=127.0.0.1